title: Intermediate Unity Sushi
hero_image: images/banner.png
description: Make a 3D space game using the Unity platform.
version: 4.0.0
listed: false
copyedit: false
last_tested: "2018-07-17"
steps:
  - title: Introduction
  - title: What you will need
  - title: Creating Your Game World
  - title: Moving the Player
  - title: Creating Obstacles
  - title: Creating Projectiles
  - title: Detecting Collisions
  - title: Display the score
  - title: Sharing Your Game
  - title: Go Further
