title: Intermediate Unity Sushi
hero_image: images/banner.png
description: Make a 3D space game using the Unity platform.
version: 4.0.0
listed: false
copyedit: false
last_tested: "2018-07-17"
steps:
  - title: Introduction
  - title: Getting started
  - title: Creating your game world
  - title: Moving the player
  - title: Creating obstacles
  - title: Creating lasers
  - title: Detecting collisions
  - title: Display the score
  - title: Sharing Your Game
  - title: "Challenge: Keyboard controls"
    challenge: true